### ISSUE TITLE
Customer journey - reg

### ISSUE THREAD

**Issue by cyrusjetson** [IBM-EPBL/IBM-Project-2500-1658472881#5]
@rp3062002

**Comment by rp3062002** [comment]
Jetson Elam enake assign ayirku change panu nenga elarum konja work
eduthukonga ekam nane epdi pana

**Comment by rp3062002** [comment]
Sorry bro epa than pathen task progress la previous mail ignore paniru

**Comment by cyrusjetson** [comment]
kk



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
10/30/22,
09:18:36 PM

**Comment by cyrusjetson** [comment]
ok da..

**Comment by saravanan-mari** [comment]
ennda ithu
